/**
 * Minimal Telegram Bot API client over `fetch`: long-polling `getUpdates`,
 * `sendMessage` with HTML or plain parse modes, `sendChatAction`, and `getMe`.
 * The token is embedded in the request URL, so every error path redacts it.
 * @module telegram/client
 */
/** Telegram user object (sender of a message). */
export interface TelegramUser {
    readonly id: number;
    readonly first_name?: string;
    readonly username?: string;
    readonly is_bot?: boolean;
}
/** Telegram chat object (private chat, group, or channel). */
export interface TelegramChat {
    readonly id: number;
    readonly type: string;
    readonly title?: string;
    readonly username?: string;
    readonly first_name?: string;
}
/** Common Telegram-hosted file identity. */
export interface TelegramFileReference {
    readonly file_id: string;
    readonly file_unique_id: string;
    readonly file_size?: number;
}
/** One available resolution of a Telegram photo. */
export interface TelegramPhotoSize extends TelegramFileReference {
    readonly width: number;
    readonly height: number;
}
/** A general Telegram document; the bridge admits only supported raster images. */
export interface TelegramDocument extends TelegramFileReference {
    readonly file_name?: string;
    readonly mime_type?: string;
}
/** Telegram message object; only the fields used by this plugin are modeled. */
export interface TelegramMessage {
    readonly message_id: number;
    readonly chat: TelegramChat;
    readonly from?: TelegramUser;
    readonly text?: string;
    readonly caption?: string;
    readonly photo?: readonly TelegramPhotoSize[];
    readonly document?: TelegramDocument;
    readonly media_group_id?: string;
    readonly reply_to_message?: TelegramMessage;
    readonly date: number;
}
/** File metadata returned by Telegram's `getFile`. */
export interface TelegramFile extends TelegramFileReference {
    readonly file_path?: string;
}
/** Fully downloaded Telegram file plus the metadata used to obtain it. */
export interface TelegramDownloadedFile {
    readonly file: TelegramFile;
    readonly data: Uint8Array;
}
/** One callback generated by an inline-keyboard button. */
export interface TelegramCallbackQuery {
    readonly id: string;
    readonly from: TelegramUser;
    readonly message?: TelegramMessage;
    readonly data?: string;
}
/** Inline button whose opaque callback payload is returned to the bot. */
export interface TelegramInlineKeyboardButton {
    readonly text: string;
    readonly callback_data: string;
}
/** Inline keyboard attached below a bot message. */
export interface TelegramInlineKeyboardMarkup {
    readonly inline_keyboard: readonly (readonly TelegramInlineKeyboardButton[])[];
}
/** Ask Telegram clients to open a reply composer for the bot message. */
export interface TelegramForceReply {
    readonly force_reply: true;
    readonly input_field_placeholder?: string;
    readonly selective?: boolean;
}
/** Reply-markup shapes used by the question flow. */
export type TelegramReplyMarkup = TelegramInlineKeyboardMarkup | TelegramForceReply;
/** Telegram update envelope for text messages and inline-button callbacks. */
export interface TelegramUpdate {
    readonly update_id: number;
    readonly message?: TelegramMessage;
    readonly callback_query?: TelegramCallbackQuery;
}
/** Runtime seam surface tests substitute with a fake. */
export interface TelegramClientLike {
    /** Fetch the bot identity; validates the token. */
    getMe(signal?: AbortSignal): Promise<TelegramUser>;
    /** Long-poll for updates at or after `offset`. */
    getUpdates(offset?: number, signal?: AbortSignal): Promise<TelegramUpdate[]>;
    /** Send a message, optionally with HTML parse mode. */
    sendMessage(chatId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal, replyMarkup?: TelegramReplyMarkup): Promise<TelegramMessage>;
    /** Send a chat action such as `typing`. */
    sendChatAction(chatId: number, action: string, signal?: AbortSignal): Promise<boolean>;
    /** Register the bot's slash-command list (shown in the Telegram UI). */
    setMyCommands(commands: Array<{
        command: string;
        description: string;
    }>, signal?: AbortSignal): Promise<boolean>;
    /** Edit a previously sent message, optionally with HTML parse mode. */
    editMessageText(chatId: number, messageId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal): Promise<TelegramMessage>;
    /** Replace or remove the inline keyboard below a message. */
    editMessageReplyMarkup(chatId: number, messageId: number, replyMarkup?: TelegramInlineKeyboardMarkup, signal?: AbortSignal): Promise<TelegramMessage>;
    /** Acknowledge a callback so Telegram dismisses the button progress spinner. */
    answerCallbackQuery(callbackQueryId: string, text?: string, showAlert?: boolean, signal?: AbortSignal): Promise<boolean>;
    /** Delete a previously sent message. */
    deleteMessage(chatId: number, messageId: number, signal?: AbortSignal): Promise<boolean>;
    /** Delete up to 100 messages from one chat in a single request. */
    deleteMessages(chatId: number, messageIds: readonly number[], signal?: AbortSignal): Promise<boolean>;
    /** Resolve and download one Telegram-hosted file under an explicit byte cap. */
    downloadFile(fileId: string, maxBytes: number, signal?: AbortSignal): Promise<TelegramDownloadedFile>;
}
/** Options for {@link TelegramClient}. */
export interface TelegramClientOptions {
    /** HTTP client seam; production uses the global `fetch`. */
    fetch?: typeof fetch;
    /** API base URL; production uses the public Bot API. */
    baseUrl?: string;
    /** Long-polling timeout in seconds; production default is 30. */
    pollingTimeoutSec?: number;
}
/**
 * Minimal Bot API client. All methods throw on transport failure or a
 * non-`ok` response; thrown messages never contain the token.
 */
export declare class TelegramClient implements TelegramClientLike {
    private readonly token;
    private readonly fetchImpl;
    private readonly baseUrl;
    /** Long-polling timeout in seconds; controls each getUpdates call. */
    readonly pollingTimeoutSec: number;
    /**
     * @param token - bot token from @BotFather.
     * @param options - client options.
     */
    constructor(token: string, options?: TelegramClientOptions);
    private url;
    /** Build a token-bearing download URL; callers must redact every failure path. */
    private fileUrl;
    /** POST `method` with `body`; throws on transport failure or a non-ok response. */
    private call;
    /**
     * Fetch the bot identity; fails when the token is invalid.
     * @returns the bot user object.
     */
    getMe(signal?: AbortSignal): Promise<TelegramUser>;
    /**
     * Long-poll for message and callback updates. Pass the previous update id plus one to
     * acknowledge already-seen updates; `undefined` asks for any pending update.
     * @param offset - the update id to start from.
     * @returns the batch of updates received within the polling timeout.
     */
    getUpdates(offset?: number, signal?: AbortSignal): Promise<TelegramUpdate[]>;
    /**
     * Send a text message, optionally with HTML parse mode.
     * @param chatId - target chat id.
     * @param text - the message text.
     * @param parseMode - `HTML` when the text is Telegram-HTML, else plain text.
     * @returns the delivered message object.
     */
    sendMessage(chatId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal, replyMarkup?: TelegramReplyMarkup): Promise<TelegramMessage>;
    /**
     * Send a chat action such as `typing`; Telegram shows it briefly while a
     * real message is on the way.
     * @param chatId - target chat id.
     * @param action - the action name (for example `typing`).
     * @returns whether the action was accepted.
     */
    sendChatAction(chatId: number, action: string, signal?: AbortSignal): Promise<boolean>;
    /**
     * Register the bot's slash-command list; Telegram shows it in the `/` menu.
     * @param commands - `{ command, description }` pairs (command without the leading slash).
     * @returns whether the registration was accepted.
     */
    setMyCommands(commands: Array<{
        command: string;
        description: string;
    }>, signal?: AbortSignal): Promise<boolean>;
    editMessageText(chatId: number, messageId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal): Promise<TelegramMessage>;
    editMessageReplyMarkup(chatId: number, messageId: number, replyMarkup?: TelegramInlineKeyboardMarkup, signal?: AbortSignal): Promise<TelegramMessage>;
    answerCallbackQuery(callbackQueryId: string, text?: string, showAlert?: boolean, signal?: AbortSignal): Promise<boolean>;
    deleteMessage(chatId: number, messageId: number, signal?: AbortSignal): Promise<boolean>;
    deleteMessages(chatId: number, messageIds: readonly number[], signal?: AbortSignal): Promise<boolean>;
    /**
     * Resolve a Telegram `file_id` and download it without ever buffering more
     * than the caller-approved limit. The public Bot API currently imposes its
     * own 20 MiB ceiling; a local Bot API server may allow more.
     */
    downloadFile(fileId: string, maxBytes: number, signal?: AbortSignal): Promise<TelegramDownloadedFile>;
}
