/**
 * Minimal Telegram Bot API client over `fetch`: long-polling `getUpdates`,
 * `sendMessage` with HTML or plain parse modes, `sendChatAction`, and `getMe`.
 * The token is embedded in the request URL, so every error path redacts it.
 * @module telegram/client
 */

/** Telegram user object (sender of a message). */
export interface TelegramUser {
  readonly id: number
  readonly first_name?: string
  readonly username?: string
  readonly is_bot?: boolean
}

/** Telegram chat object (private chat, group, or channel). */
export interface TelegramChat {
  readonly id: number
  readonly type: string
  readonly title?: string
  readonly username?: string
  readonly first_name?: string
}

/** Common Telegram-hosted file identity. */
export interface TelegramFileReference {
  readonly file_id: string
  readonly file_unique_id: string
  readonly file_size?: number
}

/** One available resolution of a Telegram photo. */
export interface TelegramPhotoSize extends TelegramFileReference {
  readonly width: number
  readonly height: number
}

/** A general Telegram document; the bridge admits only supported raster images. */
export interface TelegramDocument extends TelegramFileReference {
  readonly file_name?: string
  readonly mime_type?: string
}

/** Telegram message object; only the fields used by this plugin are modeled. */
export interface TelegramMessage {
  readonly message_id: number
  readonly chat: TelegramChat
  readonly from?: TelegramUser
  readonly text?: string
  readonly caption?: string
  readonly photo?: readonly TelegramPhotoSize[]
  readonly document?: TelegramDocument
  readonly media_group_id?: string
  readonly reply_to_message?: TelegramMessage
  readonly date: number
}

/** File metadata returned by Telegram's `getFile`. */
export interface TelegramFile extends TelegramFileReference {
  readonly file_path?: string
}

/** Fully downloaded Telegram file plus the metadata used to obtain it. */
export interface TelegramDownloadedFile {
  readonly file: TelegramFile
  readonly data: Uint8Array
}

/** One callback generated by an inline-keyboard button. */
export interface TelegramCallbackQuery {
  readonly id: string
  readonly from: TelegramUser
  readonly message?: TelegramMessage
  readonly data?: string
}

/** Inline button whose opaque callback payload is returned to the bot. */
export interface TelegramInlineKeyboardButton {
  readonly text: string
  readonly callback_data: string
}

/** Inline keyboard attached below a bot message. */
export interface TelegramInlineKeyboardMarkup {
  readonly inline_keyboard: readonly (readonly TelegramInlineKeyboardButton[])[]
}

/** Ask Telegram clients to open a reply composer for the bot message. */
export interface TelegramForceReply {
  readonly force_reply: true
  readonly input_field_placeholder?: string
  readonly selective?: boolean
}

/** Reply-markup shapes used by the question flow. */
export type TelegramReplyMarkup = TelegramInlineKeyboardMarkup | TelegramForceReply

/** Telegram update envelope for text messages and inline-button callbacks. */
export interface TelegramUpdate {
  readonly update_id: number
  readonly message?: TelegramMessage
  readonly callback_query?: TelegramCallbackQuery
  readonly stopped_message_generation?: {
    readonly chat: TelegramChat
    readonly draft_id: number
    readonly message_thread_id?: number
  }
}

/** Runtime seam surface tests substitute with a fake. */
export interface TelegramClientLike {
  /** Native Rich Markdown (including official HTML extensions); drafts expire after 30 seconds. */
  sendRichMessageDraft(chatId: number, draftId: number, markdown: string, signal?: AbortSignal): Promise<boolean>
  sendRichMessage(chatId: number, markdown: string, signal?: AbortSignal): Promise<TelegramMessage>
  /** Fetch the bot identity; validates the token. */
  getMe(signal?: AbortSignal): Promise<TelegramUser>
  /** Long-poll for updates at or after `offset`. */
  getUpdates(offset?: number, signal?: AbortSignal): Promise<TelegramUpdate[]>
  /** Send a message, optionally with HTML parse mode. */
  sendMessage(
    chatId: number,
    text: string,
    parseMode?: 'HTML',
    signal?: AbortSignal,
    replyMarkup?: TelegramReplyMarkup,
  ): Promise<TelegramMessage>
  /** Send a chat action such as `typing`. */
  sendChatAction(chatId: number, action: string, signal?: AbortSignal): Promise<boolean>
  /** Register the bot's slash-command list (shown in the Telegram UI). */
  setMyCommands(commands: Array<{ command: string; description: string }>, signal?: AbortSignal): Promise<boolean>
  /** Edit a previously sent message, optionally with HTML parse mode. */
  editMessageText(chatId: number, messageId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal): Promise<TelegramMessage>
  /** Replace or remove the inline keyboard below a message. */
  editMessageReplyMarkup(
    chatId: number,
    messageId: number,
    replyMarkup?: TelegramInlineKeyboardMarkup,
    signal?: AbortSignal,
  ): Promise<TelegramMessage>
  /** Acknowledge a callback so Telegram dismisses the button progress spinner. */
  answerCallbackQuery(callbackQueryId: string, text?: string, showAlert?: boolean, signal?: AbortSignal): Promise<boolean>
  /** Delete up to 100 messages from one chat in a single request. */
  deleteMessages(chatId: number, messageIds: readonly number[], signal?: AbortSignal): Promise<boolean>
  /** Resolve and download one Telegram-hosted file under an explicit byte cap. */
  downloadFile(fileId: string, maxBytes: number, signal?: AbortSignal): Promise<TelegramDownloadedFile>
}

/** Options for {@link TelegramClient}. */
export interface TelegramClientOptions {
  /** HTTP client seam; production uses the global `fetch`. */
  fetch?: typeof fetch
  /** API base URL; production uses the public Bot API. */
  baseUrl?: string
  /** Long-polling timeout in seconds; production default is 30. */
  pollingTimeoutSec?: number
  /** Deadline for a complete API response, including its JSON body. Defaults to 15 seconds. */
  requestTimeoutMs?: number
}

interface TelegramApiResponse<T> {
  ok?: boolean
  result?: T
  description?: string
  error_code?: number
  parameters?: { retry_after?: number }
}

/** Structured API failure; tokens are redacted before constructing this error. */
export class TelegramApiError extends Error {
  constructor(message: string, readonly code: number, readonly retryAfter?: number) {
    super(message)
    this.name = 'TelegramApiError'
  }
}

/** Replace the token with a placeholder in an error text. */
function redactToken(text: string, token: string): string {
  return text.split(token).join('***')
}

/** Strip the bot token from any thrown value before it is logged. */
function redactedMessage(error: unknown, token: string): string {
  const text = error instanceof Error ? error.message : String(error)
  return redactToken(text, token)
}

/**
 * Minimal Bot API client. All methods throw on transport failure or a
 * non-`ok` response; thrown messages never contain the token.
 */
export class TelegramClient implements TelegramClientLike {
  private readonly token: string
  private readonly fetchImpl: typeof fetch
  private readonly baseUrl: string
  /** Long-polling timeout in seconds; controls each getUpdates call. */
  readonly pollingTimeoutSec: number
  private readonly requestTimeoutMs: number

  /**
   * @param token - bot token from @BotFather.
   * @param options - client options.
   */
  constructor(token: string, options: TelegramClientOptions = {}) {
    const normalizedToken = token.trim()
    if (normalizedToken === '') throw new Error('telegram client: token must not be empty')
    const pollingTimeoutSec = options.pollingTimeoutSec ?? 30
    if (!Number.isSafeInteger(pollingTimeoutSec) || pollingTimeoutSec < 1) {
      throw new Error('telegram client: pollingTimeoutSec must be a positive integer')
    }
    this.token = normalizedToken
    this.fetchImpl = options.fetch ?? globalThis.fetch
    this.baseUrl = (options.baseUrl ?? 'https://api.telegram.org').replace(/\/+$/, '')
    this.pollingTimeoutSec = pollingTimeoutSec
    this.requestTimeoutMs = options.requestTimeoutMs ?? 15000
    if (!Number.isSafeInteger(this.requestTimeoutMs) || this.requestTimeoutMs < 1) {
      throw new RangeError('telegram client: requestTimeoutMs must be a positive integer')
    }
  }

  private url(method: string): string {
    return `${this.baseUrl}/bot${this.token}/${method}`
  }

  /** Build a token-bearing download URL; callers must redact every failure path. */
  private fileUrl(filePath: string): string {
    return `${this.baseUrl}/file/bot${this.token}/${filePath.replace(/^\/+/, '')}`
  }

  /** POST `method` with `body`; throws on transport failure or a non-ok response. */
  private async call<T>(method: string, body: Record<string, unknown>, signal?: AbortSignal, retries = 0): Promise<T> {
    let response: Response
    let payload: TelegramApiResponse<T> | null
    try {
      const timeout = method === 'getUpdates'
        ? this.pollingTimeoutSec * 1000 + this.requestTimeoutMs
        : method.endsWith('Draft') ? Math.min(5000, this.requestTimeoutMs) : this.requestTimeoutMs
      const result = await this.requestWithin(timeout, signal, async requestSignal => {
        const response = await this.fetchImpl(this.url(method), {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(body),
          signal: requestSignal,
        })
        let payload: TelegramApiResponse<T> | null
        try {
          payload = await response.json() as TelegramApiResponse<T>
        } catch {
          requestSignal.throwIfAborted()
          payload = null
        }
        return { response, payload }
      })
      response = result.response
      payload = result.payload
    } catch (error) {
      throw new Error(`telegram ${method} transport error: ${redactedMessage(error, this.token)}`)
    }
    if (!response.ok || payload?.ok !== true) {
      const description = payload?.description
        ?? (payload === null ? `invalid JSON response (HTTP ${response.status})` : `HTTP ${response.status}`)
      const code = payload?.error_code ?? response.status
      const retryAfter = payload?.parameters?.retry_after
      // Only explicit flood-control rejections are safe to retry: transport failures
      // may have delivered a message already. Drafts are retried by the coalescer.
      if (code === 429 && retries < 2 && !method.endsWith('Draft')
        && typeof retryAfter === 'number' && Number.isFinite(retryAfter) && retryAfter >= 0 && retryAfter <= 30) {
        await new Promise<void>((resolve, reject) => {
          const onAbort = (): void => { clearTimeout(timer); reject(signal?.reason ?? new Error('aborted')) }
          const timer = setTimeout(() => { signal?.removeEventListener('abort', onAbort); resolve() }, Math.max(1000, retryAfter * 1000))
          if (signal?.aborted) onAbort()
          else signal?.addEventListener('abort', onAbort, { once: true })
        })
        return this.call<T>(method, body, signal, retries + 1)
      }
      throw new TelegramApiError(`telegram ${method} failed: ${redactToken(description, this.token)}`, code, retryAfter)
    }
    if (!Object.hasOwn(payload, 'result')) {
      throw new Error(`telegram ${method} failed: response omitted result`)
    }
    return payload.result as T
  }

  /** A stalled fetch/body must never hold the chat's delivery queue indefinitely. */
  private async requestWithin<T>(timeoutMs: number, signal: AbortSignal | undefined,
    task: (signal: AbortSignal) => Promise<T>): Promise<T> {
    const timeout = new AbortController()
    const combined = signal === undefined ? timeout.signal : AbortSignal.any([signal, timeout.signal])
    const timer = setTimeout(() => timeout.abort(new Error(`request timed out after ${timeoutMs}ms`)), timeoutMs)
    let onAbort: (() => void) | undefined
    try {
      combined.throwIfAborted()
      const cancelled = new Promise<never>((_resolve, reject) => {
        onAbort = () => reject(combined.reason)
        combined.addEventListener('abort', onAbort, { once: true })
      })
      // The race also covers transports that ignore cancellation or never finish
      // reading their response body. The real fetch still receives the abort.
      return await Promise.race([task(combined), cancelled])
    } finally {
      clearTimeout(timer)
      if (onAbort !== undefined) combined.removeEventListener('abort', onAbort)
    }
  }

  /**
   * Fetch the bot identity; fails when the token is invalid.
   * @returns the bot user object.
   */
  getMe(signal?: AbortSignal): Promise<TelegramUser> {
    return this.call<TelegramUser>('getMe', {}, signal)
  }

  /**
   * Long-poll for message and callback updates. Pass the previous update id plus one to
   * acknowledge already-seen updates; `undefined` asks for any pending update.
   * @param offset - the update id to start from.
   * @returns the batch of updates received within the polling timeout.
   */
  getUpdates(offset?: number, signal?: AbortSignal): Promise<TelegramUpdate[]> {
    const body: Record<string, unknown> = {
      timeout: this.pollingTimeoutSec,
      allowed_updates: ['message', 'callback_query', 'stopped_message_generation'],
    }
    if (offset !== undefined) body.offset = offset
    return this.call<TelegramUpdate[]>('getUpdates', body, signal)
  }

  /**
   * Send a text message, optionally with HTML parse mode.
   * @param chatId - target chat id.
   * @param text - the message text.
   * @param parseMode - `HTML` when the text is Telegram-HTML, else plain text.
   * @returns the delivered message object.
   */
  sendMessage(
    chatId: number,
    text: string,
    parseMode?: 'HTML',
    signal?: AbortSignal,
    replyMarkup?: TelegramReplyMarkup,
  ): Promise<TelegramMessage> {
    const body: Record<string, unknown> = { chat_id: chatId, text }
    if (parseMode !== undefined) body.parse_mode = parseMode
    if (replyMarkup !== undefined) body.reply_markup = replyMarkup
    return this.call<TelegramMessage>('sendMessage', body, signal)
  }

  /**
   * Send a chat action such as `typing`; Telegram shows it briefly while a
   * real message is on the way.
   * @param chatId - target chat id.
   * @param action - the action name (for example `typing`).
   * @returns whether the action was accepted.
   */
  sendChatAction(chatId: number, action: string, signal?: AbortSignal): Promise<boolean> {
    return this.call<boolean>('sendChatAction', { chat_id: chatId, action }, signal)
  }

  sendRichMessageDraft(chatId: number, draftId: number, markdown: string, signal?: AbortSignal): Promise<boolean> {
    return this.call('sendRichMessageDraft', {
      chat_id: chatId, draft_id: draftId, rich_message: { markdown }, can_stop: true,
    }, signal)
  }

  sendRichMessage(chatId: number, markdown: string, signal?: AbortSignal): Promise<TelegramMessage> {
    return this.call('sendRichMessage', { chat_id: chatId, rich_message: { markdown } }, signal)
  }

  /**
   * Register the bot's slash-command list; Telegram shows it in the `/` menu.
   * @param commands - `{ command, description }` pairs (command without the leading slash).
   * @returns whether the registration was accepted.
   */
  setMyCommands(commands: Array<{ command: string; description: string }>, signal?: AbortSignal): Promise<boolean> {
    return this.call<boolean>('setMyCommands', { commands }, signal)
  }

  editMessageText(chatId: number, messageId: number, text: string, parseMode?: 'HTML', signal?: AbortSignal): Promise<TelegramMessage> {
    const body: Record<string, unknown> = { chat_id: chatId, message_id: messageId, text }
    if (parseMode !== undefined) body.parse_mode = parseMode
    return this.call<TelegramMessage>('editMessageText', body, signal)
  }

  editMessageReplyMarkup(
    chatId: number,
    messageId: number,
    replyMarkup: TelegramInlineKeyboardMarkup = { inline_keyboard: [] },
    signal?: AbortSignal,
  ): Promise<TelegramMessage> {
    return this.call<TelegramMessage>('editMessageReplyMarkup', {
      chat_id: chatId,
      message_id: messageId,
      reply_markup: replyMarkup,
    }, signal)
  }

  answerCallbackQuery(
    callbackQueryId: string,
    text?: string,
    showAlert?: boolean,
    signal?: AbortSignal,
  ): Promise<boolean> {
    const body: Record<string, unknown> = { callback_query_id: callbackQueryId }
    if (text !== undefined) body.text = text
    if (showAlert !== undefined) body.show_alert = showAlert
    return this.call<boolean>('answerCallbackQuery', body, signal)
  }

  deleteMessages(chatId: number, messageIds: readonly number[], signal?: AbortSignal): Promise<boolean> {
    if (messageIds.length < 1 || messageIds.length > 100) {
      throw new RangeError('telegram deleteMessages: messageIds must contain from 1 to 100 entries')
    }
    return this.call<boolean>('deleteMessages', {
      chat_id: chatId,
      message_ids: [...messageIds],
    }, signal)
  }

  /**
   * Resolve a Telegram `file_id` and download it without ever buffering more
   * than the caller-approved limit. The public Bot API currently imposes its
   * own 20 MiB ceiling; a local Bot API server may allow more.
   */
  async downloadFile(fileId: string, maxBytes: number, signal?: AbortSignal): Promise<TelegramDownloadedFile> {
    if (!Number.isSafeInteger(maxBytes) || maxBytes < 1) {
      throw new RangeError('telegram downloadFile: maxBytes must be a positive safe integer')
    }
    const file = await this.call<TelegramFile>('getFile', { file_id: fileId }, signal)
    if (file.file_path === undefined || file.file_path === '') {
      throw new Error('telegram getFile failed: response omitted file_path')
    }
    if (file.file_size !== undefined && file.file_size > maxBytes) {
      throw new Error(`telegram downloadFile failed: file exceeds ${maxBytes} bytes`)
    }
    let response: Response
    try {
      response = await this.fetchImpl(this.fileUrl(file.file_path), { signal })
    } catch (error) {
      throw new Error(`telegram downloadFile transport error: ${redactedMessage(error, this.token)}`)
    }
    if (!response.ok) {
      throw new Error(`telegram downloadFile failed: HTTP ${response.status}`)
    }
    const declaredLength = Number(response.headers.get('content-length'))
    if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
      try { await response.body?.cancel() } catch { /* best-effort release */ }
      throw new Error(`telegram downloadFile failed: file exceeds ${maxBytes} bytes`)
    }
    const reader = response.body?.getReader()
    if (reader === undefined) throw new Error('telegram downloadFile failed: response omitted body')
    const chunks: Uint8Array[] = []
    let length = 0
    try {
      for (;;) {
        const next = await reader.read()
        if (next.done) break
        length += next.value.byteLength
        if (length > maxBytes) {
          await reader.cancel()
          throw new Error(`telegram downloadFile failed: file exceeds ${maxBytes} bytes`)
        }
        chunks.push(next.value)
      }
    } catch (error) {
      const redacted = redactedMessage(error, this.token)
      if (/telegram downloadFile failed:/.test(redacted)) throw new Error(redacted)
      throw new Error(`telegram downloadFile transport error: ${redacted}`)
    } finally {
      reader.releaseLock()
    }
    const data = new Uint8Array(length)
    let offset = 0
    for (const chunk of chunks) {
      data.set(chunk, offset)
      offset += chunk.byteLength
    }
    return { file, data }
  }
}
